version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    target-branch: "develop"
    open-pull-requests-limit: 20
    reviewers: 
        - "mikekubn"
    schedule:
      interval: "weekly"
